In [4]:
import os

os.makedirs(os.path.join('\\', 'data'), exist_ok=True)
data_file = os.path.join('\\', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:  # 打开或者没有则创建文件
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [5]:
import pandas as pd

data = pd.read_csv(data_file)  # 将文件储存到data变量中
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [8]:
# 处理缺少值
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())  # 将数值类缺少值处理为均值
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [9]:
inputs = pd.get_dummies(inputs, dummy_na=True)  # get_dummies函数将字符串类数据处理为布尔类
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [10]:
import torch

X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)  # 将数据储存为张量
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [11]:
data = pd.read_csv(data_file)  # 将文件储存到data变量中
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [14]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())  # 将数值类缺少值处理为均值
inputs = inputs.dropna(axis=1)  # 移除具有缺少值的列
print(inputs)

   NumRooms
0       3.0
1       2.0
2       4.0
3       3.0


In [15]:
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)  # 将数据储存为张量
X, y

(tensor([[3.],
         [2.],
         [4.],
         [3.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))