In [5]:
# 调用torch模组
import torch

In [2]:
# 生成张量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# 显示张量大小
x.shape

torch.Size([12])

In [4]:
# 显示张量中元素的总数
x.numel()

12

In [6]:
# 改变张量形状
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
# 生成元素都为0的维度为（2，3，4）的张量
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
# 生成元素都为1的维度为（2，3，4）的张量
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
# 生成随机元素，维度为（2，3，4）的张量
torch.randn((2, 3, 4))

tensor([[[ 0.0474, -1.9731, -0.0401, -1.0621],
         [ 2.0200, -1.1633,  0.3690, -0.0891],
         [-0.4334, -2.8173,  1.0240,  0.3325]],

        [[ 0.9395,  2.0549, -0.5010, -0.6206],
         [-1.6994, -0.1643,  0.1558, -0.0285],
         [-0.4850,  0.0227, -0.5981,  0.4143]]])

In [13]:
# 手动生成
torch.tensor([[2, 1, 4, 4], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 4],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [16]:
# 张量的每个元素初等运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [17]:
# 张量以e为底的指数运算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [18]:
# 张量堆叠
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)  # 将X,Y进行纵向与横向堆叠

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [19]:
# 逻辑运算符
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [20]:
# 张量元素求和
X.sum()

tensor(66.)

In [23]:
# 广播机制
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b, a+b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [24]:
# 切片
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [25]:
# 切片赋值
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
# 切片赋值
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [36]:
# 重新分配内存
before = id(Y)
Y = Y + X  # 运算后地址改变
id(Y) == before  # 判断原有地址与现有地址

False

In [32]:
Z = torch.zeros_like(Y)  # 将Y所有元素变为0赋值给Z
print(Z)
print('id(Z):', id(Z))
Z[:] = X + Y
print(Z)
print('id(Z):', id(Z))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
id(Z): 2596571814224
tensor([[26., 25., 28., 27.],
        [25., 26., 27., 28.],
        [20., 21., 22., 23.]])
id(Z): 2596571814224


In [33]:
# help(torch.zeros_like)

In [34]:
# 通过X[:] = X + Y或X += Y减少内存的额外使用
before = id(X)
X += Y
id(X) == before  # 判断原有地址与现有地址

True

In [37]:
# 张量转换为numpy类型
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [38]:
# 张量转化为标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a) # item,float,int函数将张量转化成标量

(tensor([3.5000]), 3.5, 3.5, 3)

In [39]:
X < Y, X > Y

(tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [42]:
X = torch.tensor([2, 1, 0])
Y = torch.tensor([[2, 1], [1, 0], [3, 2]]).T
X + Y

tensor([[4, 2, 3],
        [3, 1, 2]])